apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: flux-emitter

build:
  artifacts:
  - image: flux_emitter
    context: .
    docker:
      dockerfile: Dockerfile
  local:
    push: false

deploy:
  kubectl:
    manifests:
    - ../deployments/flux_emitter.yaml
