apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: flux-manager

build:
  artifacts:
  - image: flux_manager
    context: .
    docker:
      dockerfile: Dockerfile
  local:
    push: false

deploy:
  kubectl:
    manifests:
    - ../deployments/flux_manager.yaml
